In [5]:
import numpy as np
items=range(10,51,10) #10~50, step 10
print(type(items)) #자료형
print(items)
print(list(items))

#넘파이배열 생성/ 위보다 사용이 편함
arr=np.array(items) # 넘파이배열로 변환
print(type(arr)) # darray
print(arr)
print(arr.shape)#차원 (5,) 

<class 'range'>
range(10, 51, 10)
[10, 20, 30, 40, 50]
<class 'numpy.ndarray'>
[10 20 30 40 50]
(5,)


In [2]:
#2차원 넘파이배열
items2=[range(1,6), range(10,51,10)] #[첫번째 자료, 두번째 자료]
arr2=np.array(items2)
print(arr2)
#2행5열의 2차원배열
print(arr2.shape) #2행 5열의 2차원 배열

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
(2, 5)


In [7]:
#numpy 배열의 연산
arr1=np.array([[70,80],[195,185]]) #2차원 배열
arr2=np.array([[50,60],[70,80]])
# arr1=[[70,80],[195,185]]
# arr2=[[50,60],[70,80]]
print(arr1+arr2) #배열의 같은 인덱스끼리 연산
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2) #실수몫(소수점 다 나옴)
print(arr1//arr2) # 정수몫

[[120 140]
 [265 265]]
[[ 20  20]
 [125 105]]
[[ 3500  4800]
 [13650 14800]]
[[1.4        1.33333333]
 [2.78571429 2.3125    ]]
[[1 1]
 [2 2]]


In [13]:
student1=[60,70,80] # 1번학생
student2=[77,88,99] # 2번학생
points=np.array([student1,student2]) # 1차원 배열을 2차원 배열로 결합
print(points)
print(points.shape)

[[60 70 80]
 [77 88 99]]
(2, 3)


In [9]:
print(points.sum()) # 전체합계
print(points.sum(axis=0)) # 열의합계(세로방향)
print(points.sum(axis=1))#행의합계(가로방향)
print(points.mean())#전체평균
print(points.mean(axis=0))#열의평균
print(points.mean(axis=1))#행의평균

474
[137 158 179]
[210 264]
79.0
[68.5 79.  89.5]
[70. 88.]


In [10]:
# 각 요소 중 큰 값을 뽑아서 새로운 배열을 생성함
arr=np.maximum(student1, student2) # 최대값만 선택된 1차원 배열
print(arr)
print(arr.sum())#합계
print(arr.mean())#평균

[77 88 99]
264
88.0


In [14]:
a=[99, 88, 77]
a.sort() # 정렬(오름차순)
print(a)
a.reverse() # 오름차순 정렬 후 내림차순 정렬
print(a)

[77, 88, 99]
[99, 88, 77]


In [15]:
print(np.sort(arr)) # 오름차순
#start:stop:step
print(np.sort(arr)[::-1]) # 내림차순

[77 88 99]
[99 88 77]


In [12]:
names = np.array(['김철수','이승호','김철수','김철수','홍상현','이영희','윤동주'])
ages=np.array([20,35,30,33,28,29,30,31,30,40,45])
#중복값을 제거한 결과값
print(np.unique(names)) # 중복값 제거한 리스트 함수
print(np.unique(ages))

['김철수' '윤동주' '이승호' '이영희' '홍상현']
[20 28 29 30 31 33 35 40 45]
