In [1]:
import numpy as np
print(np.sqrt(100))
print(np.sqrt(-4)) #not a number

10.0
nan


C:\Users\tjoeun\AppData\Local\Temp/ipykernel_15732/3491022347.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-4)) #not a number


In [2]:
a=3.7
print(type(a))
b=round(a)
print(b)
print(type(b))

<class 'float'>
4
<class 'int'>


In [3]:
a=3.7
b=int(b) #정수로 변환
print(b)
print(float(b)) #실수로 변환


4
4.0


In [4]:
a=[1,2,3,4,5]
print(min(a), max(a)) #최소, 최대

1 5


In [5]:
a=[1,2,3] #리스트를 넘파이배열로 변환
b=[4,5,6]
c=[]
d=[]
e=[]
f=[]
for i in range(3):
    c.append(a[i]+b[i])
    d.append(a[i]-b[i])
    e.append(a[i]*b[i])
    f.append(a[i]/b[i])
print(c) #곱셈
print(d)
print(e)
print(f) 



[5, 7, 9]
[-3, -3, -3]
[4, 10, 18]
[0.25, 0.4, 0.5]


In [6]:
a=np.array([1,2,3]) #리스트를 넘파이배열로 변환
b=np.array([4,5,6])
print(np.multiply(a,b)) #곱셈
print(np.max(a))
print(np.min(b))
print(np.argmax(a)) #최댓값의 인덱스
print(np.argmin(b)) #최솟값의 인덱스


[ 4 10 18]
3
4
2
0


In [7]:
a=np.array([1,2,3]) #리스트를 넘파이배열로 변환
b=np.array([4,5,6])

print(a+b) #곱셈
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [15]:
import numpy as np
np.random.seed(100) #랜덤값 고정
print(np.random.randint(9)) #0~9미만의 정수 난수
print(np.random.randint(100,150, size=5)) #100~150 미만의 5개의 정수난수


8
[124 103 139 123 115]


In [20]:
def make_numbers():
    numbers=[]
    #for i in range(10):
    while len(numbers)<10:
        num=np.random.randint(1,100)
        if num not in numbers: #중복값 거르기
            numbers.append(num)
    return numbers


In [21]:
make_numbers()


[32, 2, 14, 84, 5, 92, 60, 68, 8, 50]

In [ ]:
#인증모드로 몽고디비에 접속
conn=MongoClient('mongodb://web:1234@localhost/web')
conn

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)