In [8]:
import numpy as np
even = lambda x: x%2==0
even(np.array(range(1,11)))

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [12]:
even(11)

False

In [36]:
list(filter(even,range(1,11)))

[2, 4, 6, 8, 10]

In [9]:
#filer(함수이름, 입력값), 결과값이 True인 값들만 선택
even(np.array(range(1,11)))

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [10]:
nums=[2,1,3,5,8]

def even(n):
    if n%2==0: #n을 2로 나눈 나머지값이 0이면
        return True
    else:
        return False

result=[]
for i in nums: #리턴값이 True이면
    if even(i): #리스트에 추가
        result.append(i)
print(result)

[2, 8]


In [11]:
list(filter(lambda x:x%2==0, nums))

[2, 8]

In [13]:
a=[2*x for x in [3,5,6,8,9]]
a

[6, 10, 12, 16, 18]

In [14]:
b=[x % 3 for x in range(1,11)]
b

[1, 2, 0, 1, 2, 0, 1, 2, 0, 1]

In [17]:
[2 * x for x in [3,5,6,8,9]]

[6, 10, 12, 16, 18]

In [18]:
[x % 3 for x in range(1,11)]

[1, 2, 0, 1, 2, 0, 1, 2, 0, 1]

In [19]:
                            #짝수만 선택
[2* x for x in range(1,11) if x % 2 == 0]

[4, 8, 12, 16, 20]

In [35]:
a=[]
for x in range(1,11):
    if x % 2 == 0:
        a.append(2*x)
a


[4, 8, 12, 16, 20]

In [22]:
def triangle_area(a,h):
    return 1/2 * a * h
a=5
h=10
triangle_area(a,h)

25.0

In [23]:
np.zeros(5) #1차원 배열에 0을 채움

array([0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
#(행, 열)
a=np.zeros((2, 3, 4)) #2면 5행 5열의 2차원 배열에 0을 채움
a.shape

(2, 3, 4)

In [31]:
import numpy as np
a=np.array(range(1,6)) #1~5
h=np.array(range(1,6))
area=np.zeros((len(a), len(h))) #5행 5열의 2차원 0배열 
print(area.shape) #배열.shape 차원
for i in a:
    for j in h:
        area[i-1, j-1]=triangle_area(i,j)
area

(5, 5)


array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 1.5,  3. ,  4.5,  6. ,  7.5],
       [ 2. ,  4. ,  6. ,  8. , 10. ],
       [ 2.5,  5. ,  7.5, 10. , 12.5]])

In [26]:
triangle_area2=lambda a,h: 0.5*a*h
triangle_area2(10,5)

25.0