In [1]:
import numpy as np
import torch

li = np.array([[1,2], [3,4]])
# 넘파이배열을 텐서로 변환
tensor1 = torch.tensor(li)
tensor2 = torch.as_tensor(li)
tensor3 = torch.from_numpy(li)
print(tensor1)
print(tensor2)
print(tensor3)



tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
